export const testimonialData = [
    {
      name: "Jack",
      username: "@jack",
      flagIcon:"/icons/flags/united-states-of-america.png",
      country: "testimonials.jack.country",
      body: "testimonials.jack.body",
      img: "/images/avatars/3d-avatar-1.png",
    },
    {
      name: "Jill",
      username: "@jill",
      flagIcon:"/icons/flags/united-kingdom.png",
      country: "testimonials.jill.country",
      body: "testimonials.jill.body",
      img: "/images/avatars/3d-avatar-8.png",
    },
    {
      name: "Mahmoud",
      username: "@mahmoud",
      flagIcon:"/icons/flags/saudi-arabia.png",
      country: "testimonials.mahmoud.country",
      body: "testimonials.mahmoud.body",
      img: "/images/avatars/3d-avatar-2.png",
    },
    {
      name: "Diego",
      username: "@diego",
      flagIcon:"/icons/flags/spain.png",
      country: "testimonials.diego.country",
      body: "testimonials.diego.body",
      img: "/images/avatars/3d-avatar-3.png",
    },
    {
      name: "Mehmed",
      username: "@mehmed",
      flagIcon:"/icons/flags/turkey.png",
      country: "testimonials.mehmed.country",
      body: "testimonials.mehmed.body",
      img: "/images/avatars/3d-avatar-4.png",
    },
    {
      name: "Nour",
      username: "@nour",
      flagIcon:"/icons/flags/united-arab-emirates.png",
      country: "testimonials.nour.country",
      body: "testimonials.nour.body",
      img: "/images/avatars/3d-avatar-5.png",
    },
    {
      name: "Francesca",
      username: "@francesca",
      flagIcon:"/icons/flags/italy.png",
      country: "testimonials.francesca.country",
      body: "testimonials.francesca.body",
      img: "/images/avatars/3d-avatar-6.png",
    },
  ];